config/routes.rb
Rails.application.routes.draw do
  resources :random_access_memories
  devise_for :users
  resources :builds
  resources :graphics_processing_units
  resources :central_processing_units
  #get 'home/home'
  root 'home#home'
  #route to contact page, home controller#contact page
  get 'contact',to: 'home#contact'
  #for the form contact page to submit data
  post 'request_contact', to:'home#request_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/random_access_memory.rb
class RandomAccessMemory < ApplicationRecord
  #makes sure that the perameters have to be inialized
  validates :rammake, presence: true
  validates :ddr, presence: true
  validates :mhz, presence: true
  validates :size, presence: true
  # sets up the relationship with the build
  has_many :Build

# enum used so only values in the dropdown can be selected
  enum ddr_types:{
    ddrfour: "ddr4",
    ddrthree: "ddr3"
    }

  enum mhz_types:{
    oneksix: "1600",
    twokfour: "2400",
    threek: "3000",
    theektwo: "3200",
    theeksix: "3600"
    }

    enum size_types:{
      four: "4gb",
      eight: "8gb",
      sixteen: "16gb",
      thertytwo: "32gb",
      sixtyfour: "64gb",
      onetwentyeight: "128gb"
      }
  #used to format the select dropdown menu
  def formatted_select_text_ram
    "#{rammake}  #{ddr}  #{mhz} #{size}"
  end
end

app/controllers/random_access_memories_controller.rb
class RandomAccessMemoriesController < ApplicationController
  before_action :set_random_access_memory, only: [:show, :edit, :update, :destroy]

  # GET /random_access_memories
  # GET /random_access_memories.json
  # shows all ram in the index
  def index
    @random_access_memories = RandomAccessMemory.all
  end

  # GET /random_access_memories/1
  # GET /random_access_memories/1.json
  def show
  end

  # GET /random_access_memories/new
  def new
    @random_access_memory = RandomAccessMemory.new
  end

  # GET /random_access_memories/1/edit
  def edit
  end

  # POST /random_access_memories
  # POST /random_access_memories.json
  # creates the ram and redirects to the new ram once created
  def create
    @random_access_memory = RandomAccessMemory.new(random_access_memory_params)

    respond_to do |format|
      if @random_access_memory.save
        format.html { redirect_to @random_access_memory, notice: t('ramcon.ramcreate')  }
        format.json { render :show, status: :created, location: @random_access_memory }
      else
        format.html { render :new }
        format.json { render json: @random_access_memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /random_access_memories/1
  # PATCH/PUT /random_access_memories/1.json
  #updates a ram using form and redirects once completed
  def update
    respond_to do |format|
      if @random_access_memory.update(random_access_memory_params)
        format.html { redirect_to @random_access_memory, notice: t('ramcon.ranudt') }
        format.json { render :show, status: :ok, location: @random_access_memory }
      else
        format.html { render :edit }
        format.json { render json: @random_access_memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /random_access_memories/1
  # DELETE /random_access_memories/1.json
  #deletes an entry in ram table and redirects to ram index
  def destroy
    @random_access_memory.destroy
    respond_to do |format|
      format.html { redirect_to random_access_memories_url, notice: t('ramcon.ramdest') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_random_access_memory
      @random_access_memory = RandomAccessMemory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def random_access_memory_params
      params.require(:random_access_memory).permit(:rammake, :ddr, :mhz, :size)
    end
end

app/helpers/random_access_memories_helper.rb
module RandomAccessMemoriesHelper
end

app/views/random_access_memories/_form.html.haml
= form_for @random_access_memory do |f|
  - if @random_access_memory.errors.any?
    #error_explanation
      %h2= "#{pluralize(@random_access_memory.errors.count, "error")} prohibited this random_access_memory from being saved:"
      %ul
        - @random_access_memory.errors.full_messages.each do |message|
          %li= message


  .field
    = f.label :rammake
    = f.text_area :rammake
  .field
    = f.label :ddr
    = f.select :ddr, RandomAccessMemory.ddr_types.values.to_a

  .field
    = f.label :mhz
    = f.select :mhz, RandomAccessMemory.mhz_types.values.to_a

  .field
    = f.label :size
    = f.select :size, RandomAccessMemory.size_types.values.to_a

  .actions
    = f.submit 'Save'

app/views/random_access_memories/edit.html.haml
%h1 Editing random_access_memory

= render 'form'

= link_to 'Show', @random_access_memory
\|
= link_to 'Back', random_access_memories_path

app/views/random_access_memories/index.html.haml
%h1 Listing random_access_memories

%table
  %thead
    %tr
      %th Make
      %th DDR type
      %th Mhz
      %th Size
      %th
      %th
      %th

  %tbody
    - @random_access_memories.each do |random_access_memory|
      %tr
        %td= random_access_memory.rammake
        %td= random_access_memory.ddr
        %td= random_access_memory.mhz
        %td= random_access_memory.size
        %td= link_to 'Show', random_access_memory
        %td= link_to 'Edit', edit_random_access_memory_path(random_access_memory)
        %td= link_to 'Destroy', random_access_memory, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Random access memory', new_random_access_memory_path

app/views/random_access_memories/new.html.haml
%h1 New random_access_memory

= render 'form'

= link_to 'Back', random_access_memories_path

app/views/random_access_memories/show.html.haml
%p#notice= notice

%p
  %b Ram Make:
  = @random_access_memory.rammake
%p
  %b DDR:
  = @random_access_memory.ddr
%p
  %b Mhz:
  = @random_access_memory.mhz
%p
  %b Size:
  = @random_access_memory.size

= link_to 'Edit', edit_random_access_memory_path(@random_access_memory)
\|
= link_to 'Back', random_access_memories_path