config/routes.rb
Rails.application.routes.draw do
  resources :random_access_memories
  devise_for :users
  resources :builds
  resources :graphics_processing_units
  resources :central_processing_units
  #get 'home/home'
  root 'home#home'
  #route to contact page, home controller#contact page
  get 'contact',to: 'home#contact'
  #for the form contact page to submit data
  post 'request_contact', to:'home#request_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/central_processing_unit.rb
class CentralProcessingUnit < ApplicationRecord
  #makes sure that the perameters have to be inialized
  validates :chipmake, presence: true
  validates :chipmodel, presence: true
  # sets up relationship with build
  has_many :Build

 #used to format the select dropdown menu
  def formatted_select_text_cpu
    "#{chipmake}  #{chipmodel}"
  end
end

app/controllers/central_processing_units_controller.rb
class CentralProcessingUnitsController < ApplicationController
  before_action :set_central_processing_unit, only: [:show, :edit, :update, :destroy]

  # GET /central_processing_units
  # GET /central_processing_units.json
  # shows all cpus in the index
  def index
    @central_processing_units = CentralProcessingUnit.all
  end

  # GET /central_processing_units/1
  # GET /central_processing_units/1.json
  def show
  end

  # GET /central_processing_units/new
  def new
    @central_processing_unit = CentralProcessingUnit.new
  end

  # GET /central_processing_units/1/edit
  def edit
  end

  # POST /central_processing_units
  # POST /central_processing_units.json
  # creates the cpu and redirects to the new cpu once created
  def create
    @central_processing_unit = CentralProcessingUnit.new(central_processing_unit_params)

    respond_to do |format|
      if @central_processing_unit.save
        format.html { redirect_to @central_processing_unit, notice: t('cpucon.cpucreate') }
        format.json { render :show, status: :created, location: @central_processing_unit }
      else
        format.html { render :new }
        format.json { render json: @central_procechipmakessing_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /central_processing_units/1
  # PATCH/PUT /central_processing_units/1.json
  #updates a cpu using form and redirects once completed
  def update
    respond_to do |format|
      if @central_processing_unit.update(central_processing_unit_params)
        format.html { redirect_to @central_processing_unit, notice: t('cpucon.cpuupdt') }
        format.json { render :show, status: :ok, location: @central_processing_unit }
      else
        format.html { render :edit }
        format.json { render json: @central_processing_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /central_processing_units/1
  # DELETE /central_processing_units/1.json
  #deletes an entry in cpus table and redirects to cpu index
  def destroy
    @central_processing_unit.destroy
    respond_to do |format|
      format.html { redirect_to central_processing_units_url, notice: t('cpucon.cpudest') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_central_processing_unit
      @central_processing_unit = CentralProcessingUnit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def central_processing_unit_params
      params.require(:central_processing_unit).permit(:chipmake, :chipmodel)
    end
end

app/helpers/central_processing_units_helper.rb
module CentralProcessingUnitsHelper
end

app/views/central_processing_units/_form.html.haml
= form_for @central_processing_unit do |f|
  - if @central_processing_unit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@central_processing_unit.errors.count, "error")} #{t('gpus.saveprohib')}"
      %ul
        - @central_processing_unit.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :chipmake
    = f.text_area :chipmake
  .field
    = f.label :chipmake
    = f.text_area :chipmodel
  .actions
    = f.submit 'Save'

app/views/central_processing_units/edit.html.haml
%h1 Editing central_processing_unit

= render 'form'

= link_to 'Show', @central_processing_unit
\|
= link_to 'Back', central_processing_units_path

app/views/central_processing_units/index.html.haml
%h1 Listing Cpus

%table
  %thead
    %tr
      %th #{t('cpus.cm')}
      %th #{t('cpus.cmdl')}
      %th
      %th
      %th

  %tbody
    - @central_processing_units.each do |central_processing_unit|
      %tr
        %td= central_processing_unit.chipmake
        %td= central_processing_unit.chipmodel
        %td= link_to 'Show', central_processing_unit
        %td= link_to 'Edit', edit_central_processing_unit_path(central_processing_unit)
        %td= link_to 'Destroy', central_processing_unit, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Central processing unit', new_central_processing_unit_path

app/views/central_processing_units/new.html.haml
%h1 New central_processing_unit

= render 'form'

= link_to 'Back', central_processing_units_path

app/views/central_processing_units/show.html.haml
%p#notice= notice

%p
  %b Chipmake:
  = @central_processing_unit.chipmake
%p
  %b Chipmodel:
  = @central_processing_unit.chipmodel

= link_to 'Edit', edit_central_processing_unit_path(@central_processing_unit)
\|
= link_to 'Back', central_processing_units_path