config/routes.rb
Rails.application.routes.draw do
  resources :random_access_memories
  devise_for :users
  resources :builds
  resources :graphics_processing_units
  resources :central_processing_units
  #get 'home/home'
  root 'home#home'
  #route to contact page, home controller#contact page
  get 'contact',to: 'home#contact'
  #for the form contact page to submit data
  post 'request_contact', to:'home#request_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/build.rb
class Build < ApplicationRecord
  # sets up the relationship between the components and the build
  has_one :CentralProcessingUnit
  has_one :GraphicsProcessingUnit
  has_one :RandomAccessMemory
  has_one :User
  # uses active storage to store an image for the build
  has_one_attached :picture

#makes sure that the perameters have to be inialized (have a value = not null)
  validates :title, presence: true
  validates :cpu_id, presence: true
  validates :gpu_id, presence: true
  validates :description, presence: true
  validates :ram_id, presence: true
  validates :motherboard, presence: true
  validates :cpu_cooler, presence: true
  validates :case, presence: true
  validates :power_supply, presence: true
  validates :storage, presence: true
  validates :user_id, presence: true
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :set_build, only: [:show, :edit, :update, :destroy]
  # so that only logged in users can make new builds and edit them
  before_action :authenticate_user!, only: [:new, :edit]
  # GET /builds
  # GET /builds.json
  # shows all builds in the index
  def index
    @builds = Build.all
  end

  # GET /builds/1
  # GET /builds/1.json
  def show
  end

  # GET /builds/new
  def new
    @build = Build.new
  end

  # GET /builds/1/edit
  def edit
  end

  # POST /builds
  # POST /builds.json
  # creates the build and redirects to the new build once created
  def create
    @build = Build.new(build_params)

    respond_to do |format|
      if @build.save
        format.html { redirect_to @build, notice: t('buildcon.succreat') }
        format.json { render :show, status: :created, location: @build }
      else
        format.html { render :new }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /builds/1
  # PATCH/PUT /builds/1.json
  #updates a build using form and redirects once completed
  def update
    respond_to do |format|
      if @build.update(build_params)
        format.html { redirect_to @build, notice: t('buildcon.sucupd') }
        format.json { render :show, status: :ok, location: @build }
      else
        format.html { render :edit }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /builds/1
  # DELETE /builds/1.json
  #deletes an entry in builds table and redirects to builds index
  def destroy
    @build.destroy
    respond_to do |format|
      format.html { redirect_to builds_url, notice: t('buildcon.sucdes') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_build
      @build = Build.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def build_params
      params.require(:build).permit(:title, :cpu_id, :gpu_id,:ram_id, :description, :picture, :motherboard,:cpu_cooler,:case,:power_supply,:storage, :user_id)
    end
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/views/builds/_form.html.haml
.new-build-form
  = form_for @build do |f|
    - if @build.errors.any?
      #error_explanation
        %h2= "#{pluralize(@build.errors.count, "error")} #{t('builds.builds._form.saveprohib')}"
        %ul
          - @build.errors.full_messages.each do |message|
            %li= message

    .field
      = f.label t('builds.builds._form.title')
      = f.text_field :title

    .field
      = f.label t('builds.builds._form.pic')
      = f.file_field :picture

    .field
      = f.label t('builds.builds._form.cpu')
      -# displays a dropdown menu to select a cpu storing its id
      = collection_select( :build, :cpu_id, CentralProcessingUnit.all, :id, :formatted_select_text_cpu)

    .field
      = f.label t('builds.builds._form.gpu')
      = collection_select( :build, :gpu_id, GraphicsProcessingUnit.all, :id, :formatted_select_text_gpu)

    .field
      = f.label t('builds.builds._form.ram')
      = collection_select( :build, :ram_id, RandomAccessMemory.all, :id, :formatted_select_text_ram)
    .field
      = f.label t('builds.builds._form.motherboard')
      -# text field for the rest, could be easily adapted to have a table + relationship for all components but couldnt due to time constraints
      = f.text_field :motherboard
    .field
      = f.label t('builds.builds._form.cpu_cooler')
      = f.text_field :cpu_cooler
    .field
      = f.label t('builds.builds._form.case')
      = f.text_field :case

    .field
      = f.label t('builds.builds._form.power_supply')
      = f.text_field :power_supply
    .field
      = f.label t('builds.builds._form.storage')
      = f.text_field :storage
    .field-hide
      =f.label :user_id
      -# only displays if the user isnt null/nil
      -if !(current_user.nil?)
        = f.select :user_id, [["Your user id", current_user.id]]


    .field
      = f.label t('builds.builds._form.description')
      = f.text_field :description

    .actions
      = f.submit 'Save' , :class => 'btn-custom2'

app/views/builds/edit.html.haml
%h1 #{t('builds.builds._form.edit')}

= render 'form'
%br
%br
%br
= link_to 'Show', @build, :class => 'btn-custom2'
\|
= link_to 'Back', builds_path, :class => 'btn-custom2'

app/views/builds/index.html.haml
%h1 #{t('builds.builds._form.index')}
.build-image-show
  .row
    - @builds.each do |build|
      .col-md-3
        .image-frame
          %a{href: "/builds/#{build.id}"}
            = image_tag(build.picture, size: "400x250", class: "build-show") if build.picture.attached?
            .image-caption
              %h2 #{build.title}
              #{CentralProcessingUnit.where(id: build.cpu_id).pluck(:chipmake, :chipmodel)[0]}
              #{GraphicsProcessingUnit.where(id: build.gpu_id).pluck(:aftermarketmake ,:chipmake, :chipmodel)[0]}
              #{RandomAccessMemory.where(id: build.ram_id).pluck(:rammake ,:ddr, :mhz, :size)[0]}

              -#used to display the info of the build for each picture frame, this uses jquery. 
  %br
  %br
  %br
  = link_to 'New Build', new_build_path, :class => 'btn-custom2'

app/views/builds/new.html.haml
%h1 #{t('builds.builds._form.new')}

= render 'form'
%br
%br
%br
= link_to 'Back', builds_path, :class => 'btn-custom2'

app/views/builds/show.html.haml
%p#notice= notice

.row
  .col-md-4
    = image_tag(@build.picture, size: "400x250", class: "build-show") if @build.picture.attached?

  .col-md-8
    .build-info
      %h2.build-title=  @build.title
      %h2.build-author= "Made by user :#{User.where(id: @build.user_id).pluck(:email)[0]}"
      -# gets the user email for the current build and displays it
      %h2.build-text
        %span Cpu:
        -# if the cpuid or data is nil dont show the info
        -if !(@build.cpu_id.nil? || CentralProcessingUnit.where(id: @build.cpu_id).pluck(:chipmake, :chipmodel)[0].nil?)
          - (0..2).each do |i|
            -#plucks the info from the other table using the stored id
            =CentralProcessingUnit.where(id: @build.cpu_id).pluck(:chipmake, :chipmodel)[0][i]
      %h2.build-text
        %span Gpu:
        -if !(@build.gpu_id.nil? || GraphicsProcessingUnit.where(id: @build.gpu_id).pluck(:aftermarketmake, :chipmake, :chipmodel)[0].nil?)
          - (0..3).each do |i|
            =GraphicsProcessingUnit.where(id: @build.gpu_id).pluck(:aftermarketmake, :chipmake, :chipmodel)[0][i]
      %h2.build-text
        %span Ram:
        -if !(@build.ram_id.nil?||RandomAccessMemory.where(id: @build.ram_id).pluck(:rammake ,:ddr, :mhz, :size)[0].nil?)
          - (0..3).each do |i|
            =RandomAccessMemory.where(id: @build.ram_id).pluck(:rammake ,:ddr, :mhz, :size)[0][i]
      %h3.build-text
        %span motherboard:
        =@build.motherboard
      %h3.build-text
        %span cpu_cooler:
        =@build.cpu_cooler
      %h3.build-text
        %span case:
        =@build.case
      %h3.build-text
        %span power_supply:
        =@build.power_supply
      %h3.build-text
        %span storage:
        =@build.storage
      %h5.build-desc
        %span description:
        =@build.description

%br
%br
.links.btn-group
  = link_to "Back", builds_path, :class => 'btn-custom2'
  -# does a check for user signed in, only signed in users that made the build (or the admin account) can destroy or edit
- if user_signed_in?
  - if @build.user_id == current_user.id ||current_user.id == User.where(email: "admin@builds.com").pluck(:id)[0]
    = link_to "Edit", edit_build_path(@build), :class => 'btn-custom2'
    = link_to "Delete", build_path(@build), method: :delete, data: { confirm: "Are you sure?" }, :class => 'btn-custom2'