config/routes.rb
Rails.application.routes.draw do
  resources :random_access_memories
  devise_for :users
  resources :builds
  resources :graphics_processing_units
  resources :central_processing_units
  #get 'home/home'
  root 'home#home'
  #route to contact page, home controller#contact page
  get 'contact',to: 'home#contact'
  #for the form contact page to submit data
  post 'request_contact', to:'home#request_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/graphics_processing_unit.rb
class GraphicsProcessingUnit < ApplicationRecord
  #makes sure that the perameters have to be inialized
  validates :aftermarketmake, presence: true
  validates :chipmake, presence: true
  validates :chipmodel, presence: true
  #sets up the relationship with build
  has_many :Build

  #used to format the select dropdown menu
  def formatted_select_text_gpu
    "#{aftermarketmake}  #{chipmake}  #{chipmodel}"
  end
end

app/controllers/graphics_processing_units_controller.rb
class GraphicsProcessingUnitsController < ApplicationController
  before_action :set_graphics_processing_unit, only: [:show, :edit, :update, :destroy]

  # GET /graphics_processing_units
  # GET /graphics_processing_units.json
  # shows all gpus in the index
  def index
    @graphics_processing_units = GraphicsProcessingUnit.all
  end

  # GET /graphics_processing_units/1
  # GET /graphics_processing_units/1.json
  def show
  end

  # GET /graphics_processing_units/new
  def new
    @graphics_processing_unit = GraphicsProcessingUnit.new
  end

  # GET /graphics_processing_units/1/edit
  def edit
  end

  # POST /graphics_processing_units
  # POST /graphics_processing_units.json
  # creates the gpu and redirects to the new gpu once created
  def create
    @graphics_processing_unit = GraphicsProcessingUnit.new(graphics_processing_unit_params)

    respond_to do |format|
      if @graphics_processing_unit.save
        format.html { redirect_to @graphics_processing_unit, notice: t('gpucon.gpucreate') }
        format.json { render :show, status: :created, location: @graphics_processing_unit }
      else
        format.html { render :new }
        format.json { render json: @graphics_processing_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /graphics_processing_units/1
  # PATCH/PUT /graphics_processing_units/1.json
  #updates a gpu using form and redirects once completed
  def update
    respond_to do |format|
      if @graphics_processing_unit.update(graphics_processing_unit_params)
        format.html { redirect_to @graphics_processing_unit, notice: t('gpucon.gpuupdt') }
        format.json { render :show, status: :ok, location: @graphics_processing_unit }
      else
        format.html { render :edit }
        format.json { render json: @graphics_processing_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /graphics_processing_units/1
  # DELETE /graphics_processing_units/1.json
  #deletes an entry in gpus table and redirects to gpu index
  def destroy
    @graphics_processing_unit.destroy
    respond_to do |format|
      format.html { redirect_to graphics_processing_units_url, notice: t('gpucon.gpudest') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_graphics_processing_unit
      @graphics_processing_unit = GraphicsProcessingUnit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def graphics_processing_unit_params
      params.require(:graphics_processing_unit).permit(:aftermarketmake, :chipmake, :chipmodel)
    end
end

app/helpers/graphics_processing_units_helper.rb
module GraphicsProcessingUnitsHelper
end

app/views/graphics_processing_units/_form.html.haml
= form_for @graphics_processing_unit do |f|
  - if @graphics_processing_unit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@graphics_processing_unit.errors.count, "error")} #{t('gpus.saveprohib')}"
      %ul
        - @graphics_processing_unit.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :aftermarketmake
    = f.text_area :aftermarketmake
  .field
    = f.label :chipmake
    = f.text_area :chipmake
  .field
    = f.label :chipmodel
    = f.text_area :chipmodel
  .actions
    = f.submit 'Save'

app/views/graphics_processing_units/edit.html.haml
%h1 Editing graphics_processing_unit

= render 'form'

= link_to 'Show', @graphics_processing_unit
\|
= link_to 'Back', graphics_processing_units_path

app/views/graphics_processing_units/index.html.haml
%h1 Listing graphics_processing_units

%table
  %thead
    %tr
      %th #{t('gpus.amm')}
      %th #{t('gpus.cm')}
      %th #{t('gpus.cmm')}
      %th
      %th
      %th

  %tbody
    - @graphics_processing_units.each do |graphics_processing_unit|
      %tr
        %td= graphics_processing_unit.aftermarketmake
        %td= graphics_processing_unit.chipmake
        %td= graphics_processing_unit.chipmodel
        %td= link_to 'Show', graphics_processing_unit
        %td= link_to 'Edit', edit_graphics_processing_unit_path(graphics_processing_unit)
        %td= link_to 'Destroy', graphics_processing_unit, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Graphics processing unit', new_graphics_processing_unit_path

app/views/graphics_processing_units/new.html.haml
%h1 #{t('gpus.new')}

= render 'form'

= link_to 'Back', graphics_processing_units_path

app/views/graphics_processing_units/show.html.haml
%p#notice= notice

%p
  %b #{t('gpus.amm')}
  = @graphics_processing_unit.aftermarketmake
%p
  %b #{t('gpus.cm')}
  = @graphics_processing_unit.chipmake
%p
  %b #{t('gpus.cmm')}
  = @graphics_processing_unit.chipmodel

= link_to 'Edit', edit_graphics_processing_unit_path(@graphics_processing_unit)
\|
= link_to 'Back', graphics_processing_units_path